# Generated by Django 6.0.4 on 2026-06-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Phone_No', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CarOrder',
            fields=[
                ('Order_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Car_ID', models.IntegerField()),
                ('User_Name', models.CharField(max_length=30)),
                ('User_Email', models.EmailField(max_length=254)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_No', models.CharField(max_length=15)),
                ('Address', models.TextField()),
                ('Payment_Mode', models.CharField(default='Cash', max_length=50)),
                ('Delivery_Type', models.CharField(default='Home Delivery', max_length=50)),
                ('Order_Date', models.DateField(auto_now_add=True)),
                ('Delivery_Date', models.DateField(blank=True, null=True)),
                ('Message', models.TextField(blank=True, null=True)),
                ('Status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Delivered', 'Delivered')], default='Pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CarRent',
            fields=[
                ('Rent_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Car_ID', models.IntegerField()),
                ('User_Name', models.CharField(max_length=30)),
                ('User_Email', models.EmailField(max_length=254)),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_No', models.CharField(max_length=30)),
                ('Pickup_Date', models.DateField(blank=True, null=True)),
                ('Return_Date', models.DateField(blank=True, null=True)),
                ('Address', models.TextField()),
                ('Status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Delivered', 'Delivered')], default='Pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CarSelling',
            fields=[
                ('Sell_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Car_ID', models.IntegerField()),
                ('User_Name', models.CharField(max_length=30)),
                ('User_Email', models.EmailField(max_length=254)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_No', models.CharField(max_length=15)),
                ('Status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Delivered', 'Delivered')], default='Pending', max_length=20)),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationModel',
            fields=[
                ('Notification_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Role', models.CharField(choices=[('All', 'All'), ('Admin', 'Admin'), ('Staff', 'Staff'), ('Customer', 'Customer')], max_length=20)),
                ('Title', models.CharField(max_length=100)),
                ('Message', models.TextField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('Predict_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Role', models.CharField(choices=[('Admin', 'Admin'), ('Staff', 'Staff'), ('Customer', 'Customer')], max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Make', models.CharField(max_length=30)),
                ('Model', models.CharField(max_length=30)),
                ('Year', models.IntegerField()),
                ('Engine_HP', models.IntegerField()),
                ('Engine_Cylinders', models.IntegerField()),
                ('Transmission_Type', models.CharField(max_length=30)),
                ('Driven_Wheels', models.CharField(max_length=30)),
                ('Market_Category', models.CharField(max_length=30)),
                ('Vehicle_Size', models.CharField(max_length=30)),
                ('Vehicle_Style', models.CharField(max_length=30)),
                ('highway_MPG', models.IntegerField()),
                ('city_mpg', models.IntegerField()),
                ('Popularity', models.IntegerField()),
                ('MSRP', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RecommandationHistory',
            fields=[
                ('Recommandation_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Role', models.CharField(choices=[('Admin', 'Admin'), ('Staff', 'Staff'), ('Customer', 'Customer')], max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Brand', models.CharField(max_length=30)),
                ('Model', models.CharField(max_length=30)),
                ('Data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Service_History',
            fields=[
                ('Service_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('User_Name', models.CharField(max_length=30)),
                ('User_Email', models.EmailField(max_length=254)),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_No', models.CharField(max_length=30)),
                ('Service_Type', models.CharField(max_length=30)),
                ('Brand', models.CharField(max_length=30)),
                ('Model', models.CharField(max_length=30)),
                ('Number', models.CharField(max_length=30)),
                ('Distance', models.IntegerField()),
                ('Problem', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Service_Request',
            fields=[
                ('Service_ID', models.AutoField(primary_key=True, serialize=False)),
                ('User_Name', models.CharField(max_length=30)),
                ('User_Email', models.EmailField(max_length=254)),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_No', models.CharField(max_length=30)),
                ('Service_Type', models.CharField(max_length=30)),
                ('Brand', models.CharField(max_length=30)),
                ('Model', models.CharField(max_length=30)),
                ('Number', models.CharField(max_length=30)),
                ('Distance', models.IntegerField()),
                ('Problem', models.TextField()),
                ('Status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Staff_Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Phone_No', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
    ]
